version: '3.5'

services:
  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_DB: ${MYAPP_DB_NAME:-myapp}
      POSTGRES_USER: ${MYAPP_DB_USER:-postgres}
      POSTGRES_PASSWORD: ${MYAPP_DB_PASSWORD:-secret}
    ports:
      - ${MYAPP_DB_PORT:-54321}:5432
    restart: always

#  pgadmin:
#    container_name: pgadmin_container
#    image: dpage/pgadmin4
#    environment:
#      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
#      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
#      PGADMIN_CONFIG_SERVER_MODE: 'False'
#
#    ports:
#      - "${PGADMIN_PORT:-5050}:80"
#    restart: unless-stopped
